### ISSUE TITLE
Add a method for loading config files from a different location

### ISSUE THREAD

**Issue by bitdivision** [OverlockIoT/overlock-agent-python#3]
While investigating snap packaging, it's clear that we can't just hardcode `/etc/overlock.conf` as our main settings file. We need to use a writeable location within the snap dir. Specifically $SNAP_USER_DATA.

There's no simple way to pass a filepath in externally (although load_settings does support this) since the entry point comes through uwsgi.

So this needs to be loaded from an environment variable, which we can set in the snap file. Given that all environment variables prefixed with OVERLOCK are currently loaded into the agent (and we don't want this to be loaded into settings), we either need to add a blacklist of keys (would currently only include `OVERLOCK_CONFIG_PATH`) or use a different prefix.

Alternatively, we can just let the env be loaded into settings, however down the line I can imagine a situation where we have an obscure env that isn't used very much somewhere in the code, and someone adds that key to the settings file with the same name, potentially causing issues for existing users of that env.

Thoughts @benhowes ? I'm inclined to go with a simple blacklist for the moment.

**Comment by benhowes** [comment]
@bitdivision can we not turn this upside down and only load variables from the environment which are defined in the settings file? It would mean having defaults for everything in the base settings, e.g. `node_id=null`. That would make it simple to have `OVERLOCK_` anything you can think of.

**Comment by bitdivision** [comment]
Good point. Let's do that.
